### ISSUE TITLE
Make the default TTL infinitely long

### ISSUE THREAD

**Issue by IvanGao01** [cnosdb/cnosdb#1346] opened 2023-07-11 06:08 UTC
**Describe the issue**

When I created the database and tested it with the example you provided, a large number of cases were invalid and I had to extend the TTL duration to get the cases to run, and I was hoping that if I created the database with an infinite TTL by default, I would be able to import more historical data to analyze, such as datasets from 1970 or earlier.

Of course, it's okay if Idon't change this little issue because I can set it myself and I can set the TTL duration to 100000 or longer.

This is just a small suggestion, no offense intended.

**Comment by Subsegment** [comment] 2023-07-13 08:58
Is 4-year TTL enough for you? @IvanGao01

**Comment by Benxiaohai001** [comment] 2023-07-26 09:41
version:  8a8b09a69670b4e3c484e513b179ac594254034b
The issue is fixed, close the issue.
```log
public ❯ describe database test;
+-----+-------+----------------+---------+-----------+
| TTL | SHARD | VNODE_DURATION | REPLICA | PRECISION |
+-----+-------+----------------+---------+-----------+
| INF | 1     | 365 Days       | 1       | NS        |
+-----+-------+----------------+---------+-----------+
Query took 0.002 seconds.
```

**Closed by Benxiaohai001** 2023-07-26 09:41 UTC
