### ISSUE TITLE
[Bug] Meta build lots of connection(POC)

### ISSUE THREAD

**Issue by Subsegment** [cnosdb/cnosdb#891] opened 2023-02-09 07:24 UTC
**Is your feature request related to a problem? Please describe.**
csv 2T
1 meta
3 data
run sql on any data

![c457867a625c60d5b5ead15b266d86b2](https://user-images.githubusercontent.com/74497693/217765305-9a470886-05a5-407b-a068-cd433b38eaca.png)

**Comment by Benxiaohai001** [comment] 2023-02-23 07:15
data size 2t.
1meta
3data
line proto
check conections:
<img width="901" alt="image" src="https://user-images.githubusercontent.com/40594937/220841378-75afbb77-b7cf-4860-844e-b5afd2fe739a.png">
The issue is fixed,close the issue.

**Closed by Benxiaohai001** 2023-02-23 07:15 UTC
Labels: type/bug, distribute
